# ============================================================
# TRM Architecture Config
# ============================================================

name: TRM

model_cls_path: models.trm.TRM
output_cls_path: models.trm.TRMOutputs
halting_controller_cls_path: models.halting_controller.HaltingController
criterion_cls_path: models.criterion.TRMCriterion
metrics_fn_path: models.metrics.compute_trm_metrics

config_file: config/arch/trm_config.yaml
